# Generated by Django 5.1.5 on 2025-02-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('durak', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='game_state',
            field=models.JSONField(default=dict),
        ),
    ]
